blueprint:
  name: Motion-activated Light (if off)
  description: Turn on a light, if it is off, when motion is detected.
  domain: automation
  source_url: https://github.com/qhga/ha_blueprints/motion_light_if_off.yml
  author: phga
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          filter:
            device_class: motion
            domain: binary_sensor
    light_target:
      name: Light
      selector:
          entity:
            filter:
              domain: light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 10
      selector:
        number:
          min: 0
          max: 600
          unit_of_measurement: seconds

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

condition:
  condition: state
  entity_id: !input light_target
  state: 'off'

action:
  - service: light.turn_on
    target:
      entity_id: !input light_target
  - wait_for_trigger:
      platform: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"
      for: !input no_motion_wait
  - service: light.turn_off
    target:
      entity_id: !input light_target
